name: Canary

on:
  push:
    branches:
      - main

jobs:
  canary-ic-ui-kit-static-analysis-tests:
    name: "Static Analysis Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm run bootstrap -- -- --ci --legacy-peer-deps
          npm run build

      - name: Lint commit messages
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          echo "$COMMIT_MESSAGE" | npx commitlint

      - name: Lint
        run: npm run lint

      - name: Audit
        run: npm run audit

      - name: A11y tests
        run: npm run test-a11y:ci

      - name: Unit Component tests
        run: npm run test:coverage-ci

  canary-ic-ui-kit-e2e-tests:
    name: "E2E Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm run bootstrap -- -- --ci --legacy-peer-deps

      - name: E2E tests
        run: npm run test-e2e

  canary-ic-ui-kit-publish:
    needs: [canary-ic-ui-kit-static-analysis-tests, canary-ic-ui-kit-e2e-tests]
    name: "Publish Canary Packages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          TOKEN: ${{ secrets.PUBLISH_PAT }}
          fetch-depth: "0"
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm run bootstrap -- -- --ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Publish
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          HUSKY_SKIP_HOOKS=1 npx lerna publish --no-commit-hooks -y
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  canary-ic-ui-kit-storybook-deploy:
    needs: [canary-ic-ui-kit-publish]
    name: "Canary Storybook Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm run bootstrap -- -- --ci --legacy-peer-deps

      - name: Build components and canary web-components and react storybook
        run: |
          npm run build
          npm run build-storybook:web-components
          npm run build-storybook:react

      - name: Deploy canary web components storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./packages/web-components/storybook-static
          target-folder: ./docs/web-components

      - name: Deploy canary react storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./packages/react/storybook-static
          target-folder: ./docs/react
